"""Generated by SolidWorksAI fast_mvp fixed templates; do not edit."""
from importlib.metadata import version
import json
from pathlib import Path

from build123d import (
    Align, Axis, Box, Circle, Cylinder, Pos, Rectangle, Rot,
    SlotOverall, chamfer, export_step, extrude, fillet,
)

REQUIRED_BUILD123D = '0.11.1'
DESIGN_ID = 'plate-two-holes-04778f5c73de'
DESIGN_SPEC_SHA256 = '3f58e9944ad90d5ef1d7d8baa3a0c4a392d5a9436c65260236810a42466b0809'
if version('build123d') != REQUIRED_BUILD123D:
    raise RuntimeError('unexpected build123d version')

part = Box(100.0, 60.0, 10.0, align=(Align.CENTER, Align.CENTER, Align.MIN))
_profile_001 = Pos(-30.0, 0.0, -0.1) * Circle(4.0)
_tool_001 = extrude(_profile_001, amount=10.2)
part = part - _tool_001
_profile_002 = Pos(30.0, 0.0, -0.1) * Circle(4.0)
_tool_002 = extrude(_profile_002, amount=10.2)
part = part - _tool_002

if not part.is_valid:
    raise RuntimeError('generated BREP is invalid')
if len(part.solids()) != 1:
    raise RuntimeError('generated result is not one solid')
output_path = Path(__file__).with_name('model.step')
export_step(part, output_path, timestamp='1970-01-01T00:00:00Z')
bbox = part.bounding_box()
print(json.dumps({
    'status': 'generated',
    'design_id': DESIGN_ID,
    'design_spec_sha256': DESIGN_SPEC_SHA256,
    'build123d_version': REQUIRED_BUILD123D,
    'solid_count': len(part.solids()),
    'volume_mm3': part.volume,
    'bounding_box_size_mm': [bbox.size.X, bbox.size.Y, bbox.size.Z],
}, sort_keys=True))
